// Code generated by ent, DO NOT EDIT.

package ent

import (
	"orm/ent/order"
	"orm/ent/orderreservation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 2)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   order.Table,
			Columns: order.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: order.FieldID,
			},
		},
		Type: "Order",
		Fields: map[string]*sqlgraph.FieldSpec{
			order.FieldRefID:     {Type: field.TypeString, Column: order.FieldRefID},
			order.FieldRefSource: {Type: field.TypeString, Column: order.FieldRefSource},
			order.FieldStatus:    {Type: field.TypeEnum, Column: order.FieldStatus},
			order.FieldCreatedAt: {Type: field.TypeTime, Column: order.FieldCreatedAt},
			order.FieldUpdatedAt: {Type: field.TypeTime, Column: order.FieldUpdatedAt},
			order.FieldUsedAt:    {Type: field.TypeTime, Column: order.FieldUsedAt},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   orderreservation.Table,
			Columns: orderreservation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: orderreservation.FieldID,
			},
		},
		Type: "OrderReservation",
		Fields: map[string]*sqlgraph.FieldSpec{
			orderreservation.FieldRefID:     {Type: field.TypeString, Column: orderreservation.FieldRefID},
			orderreservation.FieldRefSource: {Type: field.TypeString, Column: orderreservation.FieldRefSource},
			orderreservation.FieldCreatedAt: {Type: field.TypeTime, Column: orderreservation.FieldCreatedAt},
			orderreservation.FieldUsedAt:    {Type: field.TypeTime, Column: orderreservation.FieldUsedAt},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *OrderQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the OrderQuery builder.
func (_q *OrderQuery) Filter() *OrderFilter {
	return &OrderFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *OrderMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the OrderMutation builder.
func (m *OrderMutation) Filter() *OrderFilter {
	return &OrderFilter{config: m.config, predicateAdder: m}
}

// OrderFilter provides a generic filtering capability at runtime for OrderQuery.
type OrderFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *OrderFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *OrderFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(order.FieldID))
}

// WhereRefID applies the entql string predicate on the ref_id field.
func (f *OrderFilter) WhereRefID(p entql.StringP) {
	f.Where(p.Field(order.FieldRefID))
}

// WhereRefSource applies the entql string predicate on the ref_source field.
func (f *OrderFilter) WhereRefSource(p entql.StringP) {
	f.Where(p.Field(order.FieldRefSource))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *OrderFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(order.FieldStatus))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *OrderFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(order.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *OrderFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(order.FieldUpdatedAt))
}

// WhereUsedAt applies the entql time.Time predicate on the used_at field.
func (f *OrderFilter) WhereUsedAt(p entql.TimeP) {
	f.Where(p.Field(order.FieldUsedAt))
}

// addPredicate implements the predicateAdder interface.
func (_q *OrderReservationQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the OrderReservationQuery builder.
func (_q *OrderReservationQuery) Filter() *OrderReservationFilter {
	return &OrderReservationFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *OrderReservationMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the OrderReservationMutation builder.
func (m *OrderReservationMutation) Filter() *OrderReservationFilter {
	return &OrderReservationFilter{config: m.config, predicateAdder: m}
}

// OrderReservationFilter provides a generic filtering capability at runtime for OrderReservationQuery.
type OrderReservationFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *OrderReservationFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int predicate on the id field.
func (f *OrderReservationFilter) WhereID(p entql.IntP) {
	f.Where(p.Field(orderreservation.FieldID))
}

// WhereRefID applies the entql string predicate on the ref_id field.
func (f *OrderReservationFilter) WhereRefID(p entql.StringP) {
	f.Where(p.Field(orderreservation.FieldRefID))
}

// WhereRefSource applies the entql string predicate on the ref_source field.
func (f *OrderReservationFilter) WhereRefSource(p entql.StringP) {
	f.Where(p.Field(orderreservation.FieldRefSource))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *OrderReservationFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(orderreservation.FieldCreatedAt))
}

// WhereUsedAt applies the entql time.Time predicate on the used_at field.
func (f *OrderReservationFilter) WhereUsedAt(p entql.TimeP) {
	f.Where(p.Field(orderreservation.FieldUsedAt))
}
