// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orm/ent/orderreservation"
	"orm/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderReservationUpdate is the builder for updating OrderReservation entities.
type OrderReservationUpdate struct {
	config
	hooks    []Hook
	mutation *OrderReservationMutation
}

// Where appends a list predicates to the OrderReservationUpdate builder.
func (_u *OrderReservationUpdate) Where(ps ...predicate.OrderReservation) *OrderReservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRefID sets the "ref_id" field.
func (_u *OrderReservationUpdate) SetRefID(v string) *OrderReservationUpdate {
	_u.mutation.SetRefID(v)
	return _u
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_u *OrderReservationUpdate) SetNillableRefID(v *string) *OrderReservationUpdate {
	if v != nil {
		_u.SetRefID(*v)
	}
	return _u
}

// SetRefSource sets the "ref_source" field.
func (_u *OrderReservationUpdate) SetRefSource(v string) *OrderReservationUpdate {
	_u.mutation.SetRefSource(v)
	return _u
}

// SetNillableRefSource sets the "ref_source" field if the given value is not nil.
func (_u *OrderReservationUpdate) SetNillableRefSource(v *string) *OrderReservationUpdate {
	if v != nil {
		_u.SetRefSource(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OrderReservationUpdate) SetCreatedAt(v time.Time) *OrderReservationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OrderReservationUpdate) SetNillableCreatedAt(v *time.Time) *OrderReservationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *OrderReservationUpdate) ClearCreatedAt() *OrderReservationUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *OrderReservationUpdate) SetUsedAt(v time.Time) *OrderReservationUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *OrderReservationUpdate) SetNillableUsedAt(v *time.Time) *OrderReservationUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *OrderReservationUpdate) ClearUsedAt() *OrderReservationUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// Mutation returns the OrderReservationMutation object of the builder.
func (_u *OrderReservationUpdate) Mutation() *OrderReservationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderReservationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderReservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderReservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderReservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderReservationUpdate) check() error {
	if v, ok := _u.mutation.RefID(); ok {
		if err := orderreservation.RefIDValidator(v); err != nil {
			return &ValidationError{Name: "ref_id", err: fmt.Errorf(`ent: validator failed for field "OrderReservation.ref_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefSource(); ok {
		if err := orderreservation.RefSourceValidator(v); err != nil {
			return &ValidationError{Name: "ref_source", err: fmt.Errorf(`ent: validator failed for field "OrderReservation.ref_source": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderReservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderreservation.Table, orderreservation.Columns, sqlgraph.NewFieldSpec(orderreservation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RefID(); ok {
		_spec.SetField(orderreservation.FieldRefID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefSource(); ok {
		_spec.SetField(orderreservation.FieldRefSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(orderreservation.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(orderreservation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(orderreservation.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(orderreservation.FieldUsedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderReservationUpdateOne is the builder for updating a single OrderReservation entity.
type OrderReservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderReservationMutation
}

// SetRefID sets the "ref_id" field.
func (_u *OrderReservationUpdateOne) SetRefID(v string) *OrderReservationUpdateOne {
	_u.mutation.SetRefID(v)
	return _u
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_u *OrderReservationUpdateOne) SetNillableRefID(v *string) *OrderReservationUpdateOne {
	if v != nil {
		_u.SetRefID(*v)
	}
	return _u
}

// SetRefSource sets the "ref_source" field.
func (_u *OrderReservationUpdateOne) SetRefSource(v string) *OrderReservationUpdateOne {
	_u.mutation.SetRefSource(v)
	return _u
}

// SetNillableRefSource sets the "ref_source" field if the given value is not nil.
func (_u *OrderReservationUpdateOne) SetNillableRefSource(v *string) *OrderReservationUpdateOne {
	if v != nil {
		_u.SetRefSource(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OrderReservationUpdateOne) SetCreatedAt(v time.Time) *OrderReservationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OrderReservationUpdateOne) SetNillableCreatedAt(v *time.Time) *OrderReservationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *OrderReservationUpdateOne) ClearCreatedAt() *OrderReservationUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *OrderReservationUpdateOne) SetUsedAt(v time.Time) *OrderReservationUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *OrderReservationUpdateOne) SetNillableUsedAt(v *time.Time) *OrderReservationUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *OrderReservationUpdateOne) ClearUsedAt() *OrderReservationUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// Mutation returns the OrderReservationMutation object of the builder.
func (_u *OrderReservationUpdateOne) Mutation() *OrderReservationMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrderReservationUpdate builder.
func (_u *OrderReservationUpdateOne) Where(ps ...predicate.OrderReservation) *OrderReservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderReservationUpdateOne) Select(field string, fields ...string) *OrderReservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderReservation entity.
func (_u *OrderReservationUpdateOne) Save(ctx context.Context) (*OrderReservation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderReservationUpdateOne) SaveX(ctx context.Context) *OrderReservation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderReservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderReservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderReservationUpdateOne) check() error {
	if v, ok := _u.mutation.RefID(); ok {
		if err := orderreservation.RefIDValidator(v); err != nil {
			return &ValidationError{Name: "ref_id", err: fmt.Errorf(`ent: validator failed for field "OrderReservation.ref_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefSource(); ok {
		if err := orderreservation.RefSourceValidator(v); err != nil {
			return &ValidationError{Name: "ref_source", err: fmt.Errorf(`ent: validator failed for field "OrderReservation.ref_source": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderReservationUpdateOne) sqlSave(ctx context.Context) (_node *OrderReservation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderreservation.Table, orderreservation.Columns, sqlgraph.NewFieldSpec(orderreservation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderReservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderreservation.FieldID)
		for _, f := range fields {
			if !orderreservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderreservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RefID(); ok {
		_spec.SetField(orderreservation.FieldRefID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefSource(); ok {
		_spec.SetField(orderreservation.FieldRefSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(orderreservation.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(orderreservation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(orderreservation.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(orderreservation.FieldUsedAt, field.TypeTime)
	}
	_node = &OrderReservation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
