// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orm/ent/orderreservation"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderReservationCreate is the builder for creating a OrderReservation entity.
type OrderReservationCreate struct {
	config
	mutation *OrderReservationMutation
	hooks    []Hook
}

// SetRefID sets the "ref_id" field.
func (_c *OrderReservationCreate) SetRefID(v string) *OrderReservationCreate {
	_c.mutation.SetRefID(v)
	return _c
}

// SetRefSource sets the "ref_source" field.
func (_c *OrderReservationCreate) SetRefSource(v string) *OrderReservationCreate {
	_c.mutation.SetRefSource(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderReservationCreate) SetCreatedAt(v time.Time) *OrderReservationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderReservationCreate) SetNillableCreatedAt(v *time.Time) *OrderReservationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *OrderReservationCreate) SetUsedAt(v time.Time) *OrderReservationCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *OrderReservationCreate) SetNillableUsedAt(v *time.Time) *OrderReservationCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrderReservationCreate) SetID(v int) *OrderReservationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OrderReservationMutation object of the builder.
func (_c *OrderReservationCreate) Mutation() *OrderReservationMutation {
	return _c.mutation
}

// Save creates the OrderReservation in the database.
func (_c *OrderReservationCreate) Save(ctx context.Context) (*OrderReservation, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderReservationCreate) SaveX(ctx context.Context) *OrderReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderReservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderReservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderReservationCreate) check() error {
	if _, ok := _c.mutation.RefID(); !ok {
		return &ValidationError{Name: "ref_id", err: errors.New(`ent: missing required field "OrderReservation.ref_id"`)}
	}
	if v, ok := _c.mutation.RefID(); ok {
		if err := orderreservation.RefIDValidator(v); err != nil {
			return &ValidationError{Name: "ref_id", err: fmt.Errorf(`ent: validator failed for field "OrderReservation.ref_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RefSource(); !ok {
		return &ValidationError{Name: "ref_source", err: errors.New(`ent: missing required field "OrderReservation.ref_source"`)}
	}
	if v, ok := _c.mutation.RefSource(); ok {
		if err := orderreservation.RefSourceValidator(v); err != nil {
			return &ValidationError{Name: "ref_source", err: fmt.Errorf(`ent: validator failed for field "OrderReservation.ref_source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := orderreservation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "OrderReservation.id": %w`, err)}
		}
	}
	return nil
}

func (_c *OrderReservationCreate) sqlSave(ctx context.Context) (*OrderReservation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderReservationCreate) createSpec() (*OrderReservation, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderReservation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orderreservation.Table, sqlgraph.NewFieldSpec(orderreservation.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RefID(); ok {
		_spec.SetField(orderreservation.FieldRefID, field.TypeString, value)
		_node.RefID = value
	}
	if value, ok := _c.mutation.RefSource(); ok {
		_spec.SetField(orderreservation.FieldRefSource, field.TypeString, value)
		_node.RefSource = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(orderreservation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(orderreservation.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	return _node, _spec
}

// OrderReservationCreateBulk is the builder for creating many OrderReservation entities in bulk.
type OrderReservationCreateBulk struct {
	config
	err      error
	builders []*OrderReservationCreate
}

// Save creates the OrderReservation entities in the database.
func (_c *OrderReservationCreateBulk) Save(ctx context.Context) ([]*OrderReservation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrderReservation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderReservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderReservationCreateBulk) SaveX(ctx context.Context) []*OrderReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderReservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderReservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
