// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"orm/ent/orderreservation"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OrderReservation is the model entity for the OrderReservation schema.
type OrderReservation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RefID holds the value of the "ref_id" field.
	RefID string `json:"ref_id,omitempty"`
	// RefSource holds the value of the "ref_source" field.
	RefSource string `json:"ref_source,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// When it was taken/used; NULL = available
	UsedAt       *time.Time `json:"used_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrderReservation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case orderreservation.FieldID:
			values[i] = new(sql.NullInt64)
		case orderreservation.FieldRefID, orderreservation.FieldRefSource:
			values[i] = new(sql.NullString)
		case orderreservation.FieldCreatedAt, orderreservation.FieldUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrderReservation fields.
func (_m *OrderReservation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case orderreservation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case orderreservation.FieldRefID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ref_id", values[i])
			} else if value.Valid {
				_m.RefID = value.String
			}
		case orderreservation.FieldRefSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ref_source", values[i])
			} else if value.Valid {
				_m.RefSource = value.String
			}
		case orderreservation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case orderreservation.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = new(time.Time)
				*_m.UsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrderReservation.
// This includes values selected through modifiers, order, etc.
func (_m *OrderReservation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OrderReservation.
// Note that you need to call OrderReservation.Unwrap() before calling this method if this OrderReservation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrderReservation) Update() *OrderReservationUpdateOne {
	return NewOrderReservationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrderReservation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrderReservation) Unwrap() *OrderReservation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrderReservation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrderReservation) String() string {
	var builder strings.Builder
	builder.WriteString("OrderReservation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ref_id=")
	builder.WriteString(_m.RefID)
	builder.WriteString(", ")
	builder.WriteString("ref_source=")
	builder.WriteString(_m.RefSource)
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OrderReservations is a parsable slice of OrderReservation.
type OrderReservations []*OrderReservation
