// Code generated by ent, DO NOT EDIT.

package ent

import (
	"orm/ent/order"
	"orm/ent/orderreservation"
	"orm/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescRefID is the schema descriptor for ref_id field.
	orderDescRefID := orderFields[1].Descriptor()
	// order.RefIDValidator is a validator for the "ref_id" field. It is called by the builders before save.
	order.RefIDValidator = orderDescRefID.Validators[0].(func(string) error)
	// orderDescRefSource is the schema descriptor for ref_source field.
	orderDescRefSource := orderFields[2].Descriptor()
	// order.RefSourceValidator is a validator for the "ref_source" field. It is called by the builders before save.
	order.RefSourceValidator = orderDescRefSource.Validators[0].(func(string) error)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.DefaultID holds the default value on creation for the id field.
	order.DefaultID = orderDescID.Default.(func() uuid.UUID)
	orderreservationFields := schema.OrderReservation{}.Fields()
	_ = orderreservationFields
	// orderreservationDescRefID is the schema descriptor for ref_id field.
	orderreservationDescRefID := orderreservationFields[1].Descriptor()
	// orderreservation.RefIDValidator is a validator for the "ref_id" field. It is called by the builders before save.
	orderreservation.RefIDValidator = orderreservationDescRefID.Validators[0].(func(string) error)
	// orderreservationDescRefSource is the schema descriptor for ref_source field.
	orderreservationDescRefSource := orderreservationFields[2].Descriptor()
	// orderreservation.RefSourceValidator is a validator for the "ref_source" field. It is called by the builders before save.
	orderreservation.RefSourceValidator = orderreservationDescRefSource.Validators[0].(func(string) error)
	// orderreservationDescID is the schema descriptor for id field.
	orderreservationDescID := orderreservationFields[0].Descriptor()
	// orderreservation.IDValidator is a validator for the "id" field. It is called by the builders before save.
	orderreservation.IDValidator = orderreservationDescID.Validators[0].(func(int) error)
}
