// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockorder

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderReservationRepository creates a new instance of MockOrderReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderReservationRepository {
	mock := &MockOrderReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderReservationRepository is an autogenerated mock type for the OrderReservationRepository type
type MockOrderReservationRepository struct {
	mock.Mock
}

type MockOrderReservationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderReservationRepository) EXPECT() *MockOrderReservationRepository_Expecter {
	return &MockOrderReservationRepository_Expecter{mock: &_m.Mock}
}

// Pull provides a mock function for the type MockOrderReservationRepository
func (_mock *MockOrderReservationRepository) Pull(ctx context.Context, refSource string) (string, error) {
	ret := _mock.Called(ctx, refSource)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, refSource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, refSource)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refSource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderReservationRepository_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockOrderReservationRepository_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - refSource string
func (_e *MockOrderReservationRepository_Expecter) Pull(ctx interface{}, refSource interface{}) *MockOrderReservationRepository_Pull_Call {
	return &MockOrderReservationRepository_Pull_Call{Call: _e.mock.On("Pull", ctx, refSource)}
}

func (_c *MockOrderReservationRepository_Pull_Call) Run(run func(ctx context.Context, refSource string)) *MockOrderReservationRepository_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderReservationRepository_Pull_Call) Return(s string, err error) *MockOrderReservationRepository_Pull_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOrderReservationRepository_Pull_Call) RunAndReturn(run func(ctx context.Context, refSource string) (string, error)) *MockOrderReservationRepository_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockOrderReservationRepository
func (_mock *MockOrderReservationRepository) Push(ctx context.Context, refSource string, refID string) error {
	ret := _mock.Called(ctx, refSource, refID)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, refSource, refID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderReservationRepository_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockOrderReservationRepository_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - refSource string
//   - refID string
func (_e *MockOrderReservationRepository_Expecter) Push(ctx interface{}, refSource interface{}, refID interface{}) *MockOrderReservationRepository_Push_Call {
	return &MockOrderReservationRepository_Push_Call{Call: _e.mock.On("Push", ctx, refSource, refID)}
}

func (_c *MockOrderReservationRepository_Push_Call) Run(run func(ctx context.Context, refSource string, refID string)) *MockOrderReservationRepository_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderReservationRepository_Push_Call) Return(err error) *MockOrderReservationRepository_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderReservationRepository_Push_Call) RunAndReturn(run func(ctx context.Context, refSource string, refID string) error) *MockOrderReservationRepository_Push_Call {
	_c.Call.Return(run)
	return _c
}
