// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockorder

import (
	"context"
	"pocket-shop/internal/core/order"
	"pocket-shop/internal/core/order/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Count(ctx context.Context, input order.OrderGetInput) (int, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.OrderGetInput) (int, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.OrderGetInput) int); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.OrderGetInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockOrderRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - input order.OrderGetInput
func (_e *MockOrderRepository_Expecter) Count(ctx interface{}, input interface{}) *MockOrderRepository_Count_Call {
	return &MockOrderRepository_Count_Call{Call: _e.mock.On("Count", ctx, input)}
}

func (_c *MockOrderRepository_Count_Call) Run(run func(ctx context.Context, input order.OrderGetInput)) *MockOrderRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.OrderGetInput
		if args[1] != nil {
			arg1 = args[1].(order.OrderGetInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Count_Call) Return(n int, err error) *MockOrderRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrderRepository_Count_Call) RunAndReturn(run func(ctx context.Context, input order.OrderGetInput) (int, error)) *MockOrderRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Create(ctx context.Context, o domain.Order) (*domain.Order, error) {
	ret := _mock.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) (*domain.Order, error)); ok {
		return returnFunc(ctx, o)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) *domain.Order); ok {
		r0 = returnFunc(ctx, o)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Order) error); ok {
		r1 = returnFunc(ctx, o)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - o domain.Order
func (_e *MockOrderRepository_Expecter) Create(ctx interface{}, o interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, o)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, o domain.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Order
		if args[1] != nil {
			arg1 = args[1].(domain.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(order1 *domain.Order, err error) *MockOrderRepository_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, o domain.Order) (*domain.Order, error)) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetByID(ctx context.Context, id string) (*domain.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrderRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockOrderRepository_GetByID_Call {
	return &MockOrderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOrderRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockOrderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) Return(order1 *domain.Order, err error) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Order, error)) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecovery provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetRecovery(ctx context.Context, refSource string) ([]domain.Order, error) {
	ret := _mock.Called(ctx, refSource)

	if len(ret) == 0 {
		panic("no return value specified for GetRecovery")
	}

	var r0 []domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Order, error)); ok {
		return returnFunc(ctx, refSource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Order); ok {
		r0 = returnFunc(ctx, refSource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refSource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetRecovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecovery'
type MockOrderRepository_GetRecovery_Call struct {
	*mock.Call
}

// GetRecovery is a helper method to define mock.On call
//   - ctx context.Context
//   - refSource string
func (_e *MockOrderRepository_Expecter) GetRecovery(ctx interface{}, refSource interface{}) *MockOrderRepository_GetRecovery_Call {
	return &MockOrderRepository_GetRecovery_Call{Call: _e.mock.On("GetRecovery", ctx, refSource)}
}

func (_c *MockOrderRepository_GetRecovery_Call) Run(run func(ctx context.Context, refSource string)) *MockOrderRepository_GetRecovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetRecovery_Call) Return(orders []domain.Order, err error) *MockOrderRepository_GetRecovery_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepository_GetRecovery_Call) RunAndReturn(run func(ctx context.Context, refSource string) ([]domain.Order, error)) *MockOrderRepository_GetRecovery_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRefIDUsed provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) MarkRefIDUsed(ctx context.Context, refSource string, refIDs []string) error {
	ret := _mock.Called(ctx, refSource, refIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkRefIDUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, refSource, refIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_MarkRefIDUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRefIDUsed'
type MockOrderRepository_MarkRefIDUsed_Call struct {
	*mock.Call
}

// MarkRefIDUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - refSource string
//   - refIDs []string
func (_e *MockOrderRepository_Expecter) MarkRefIDUsed(ctx interface{}, refSource interface{}, refIDs interface{}) *MockOrderRepository_MarkRefIDUsed_Call {
	return &MockOrderRepository_MarkRefIDUsed_Call{Call: _e.mock.On("MarkRefIDUsed", ctx, refSource, refIDs)}
}

func (_c *MockOrderRepository_MarkRefIDUsed_Call) Run(run func(ctx context.Context, refSource string, refIDs []string)) *MockOrderRepository_MarkRefIDUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_MarkRefIDUsed_Call) Return(err error) *MockOrderRepository_MarkRefIDUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_MarkRefIDUsed_Call) RunAndReturn(run func(ctx context.Context, refSource string, refIDs []string) error) *MockOrderRepository_MarkRefIDUsed_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Save(ctx context.Context, o *domain.Order) error {
	ret := _mock.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Order) error); ok {
		r0 = returnFunc(ctx, o)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOrderRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - o *domain.Order
func (_e *MockOrderRepository_Expecter) Save(ctx interface{}, o interface{}) *MockOrderRepository_Save_Call {
	return &MockOrderRepository_Save_Call{Call: _e.mock.On("Save", ctx, o)}
}

func (_c *MockOrderRepository_Save_Call) Run(run func(ctx context.Context, o *domain.Order)) *MockOrderRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Order
		if args[1] != nil {
			arg1 = args[1].(*domain.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Save_Call) Return(err error) *MockOrderRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Save_Call) RunAndReturn(run func(ctx context.Context, o *domain.Order) error) *MockOrderRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
