// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockorder

import (
	"context"
	"pocket-shop/internal/core/order/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) CreateOrder(ctx context.Context, refSource string) (*domain.Order, error) {
	ret := _mock.Called(ctx, refSource)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Order, error)); ok {
		return returnFunc(ctx, refSource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Order); ok {
		r0 = returnFunc(ctx, refSource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refSource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - refSource string
func (_e *MockOrderService_Expecter) CreateOrder(ctx interface{}, refSource interface{}) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, refSource)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(ctx context.Context, refSource string)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(order *domain.Order, err error) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, refSource string) (*domain.Order, error)) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoverAvailable provides a mock function for the type MockOrderService
func (_mock *MockOrderService) DiscoverAvailable(ctx context.Context, refSource string) error {
	ret := _mock.Called(ctx, refSource)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverAvailable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refSource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_DiscoverAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverAvailable'
type MockOrderService_DiscoverAvailable_Call struct {
	*mock.Call
}

// DiscoverAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - refSource string
func (_e *MockOrderService_Expecter) DiscoverAvailable(ctx interface{}, refSource interface{}) *MockOrderService_DiscoverAvailable_Call {
	return &MockOrderService_DiscoverAvailable_Call{Call: _e.mock.On("DiscoverAvailable", ctx, refSource)}
}

func (_c *MockOrderService_DiscoverAvailable_Call) Run(run func(ctx context.Context, refSource string)) *MockOrderService_DiscoverAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_DiscoverAvailable_Call) Return(err error) *MockOrderService_DiscoverAvailable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_DiscoverAvailable_Call) RunAndReturn(run func(ctx context.Context, refSource string) error) *MockOrderService_DiscoverAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) GetOrder(ctx context.Context, id string) (*domain.Order, *string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *domain.Order
	var r1 *string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Order, *string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *string); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrderService_Expecter) GetOrder(ctx interface{}, id interface{}) *MockOrderService_GetOrder_Call {
	return &MockOrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockOrderService_GetOrder_Call) Run(run func(ctx context.Context, id string)) *MockOrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_GetOrder_Call) Return(order *domain.Order, s *string, err error) *MockOrderService_GetOrder_Call {
	_c.Call.Return(order, s, err)
	return _c
}

func (_c *MockOrderService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Order, *string, error)) *MockOrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}
