// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockport

import (
	"context"
	"pocket-shop/internal/port"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEZClient creates a new instance of MockEZClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEZClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEZClient {
	mock := &MockEZClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEZClient is an autogenerated mock type for the EZClient type
type MockEZClient struct {
	mock.Mock
}

type MockEZClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEZClient) EXPECT() *MockEZClient_Expecter {
	return &MockEZClient_Expecter{mock: &_m.Mock}
}

// CreateInstantOrder provides a mock function for the type MockEZClient
func (_mock *MockEZClient) CreateInstantOrder(ctx context.Context, clientOrderID string) (*port.Order, error) {
	ret := _mock.Called(ctx, clientOrderID)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstantOrder")
	}

	var r0 *port.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*port.Order, error)); ok {
		return returnFunc(ctx, clientOrderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *port.Order); ok {
		r0 = returnFunc(ctx, clientOrderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clientOrderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEZClient_CreateInstantOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstantOrder'
type MockEZClient_CreateInstantOrder_Call struct {
	*mock.Call
}

// CreateInstantOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - clientOrderID string
func (_e *MockEZClient_Expecter) CreateInstantOrder(ctx interface{}, clientOrderID interface{}) *MockEZClient_CreateInstantOrder_Call {
	return &MockEZClient_CreateInstantOrder_Call{Call: _e.mock.On("CreateInstantOrder", ctx, clientOrderID)}
}

func (_c *MockEZClient_CreateInstantOrder_Call) Run(run func(ctx context.Context, clientOrderID string)) *MockEZClient_CreateInstantOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEZClient_CreateInstantOrder_Call) Return(order *port.Order, err error) *MockEZClient_CreateInstantOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockEZClient_CreateInstantOrder_Call) RunAndReturn(run func(ctx context.Context, clientOrderID string) (*port.Order, error)) *MockEZClient_CreateInstantOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetFirstRedeemCode provides a mock function for the type MockEZClient
func (_mock *MockEZClient) GetFirstRedeemCode(ctx context.Context, refID string) (string, error) {
	ret := _mock.Called(ctx, refID)

	if len(ret) == 0 {
		panic("no return value specified for GetFirstRedeemCode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, refID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, refID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEZClient_GetFirstRedeemCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstRedeemCode'
type MockEZClient_GetFirstRedeemCode_Call struct {
	*mock.Call
}

// GetFirstRedeemCode is a helper method to define mock.On call
//   - ctx context.Context
//   - refID string
func (_e *MockEZClient_Expecter) GetFirstRedeemCode(ctx interface{}, refID interface{}) *MockEZClient_GetFirstRedeemCode_Call {
	return &MockEZClient_GetFirstRedeemCode_Call{Call: _e.mock.On("GetFirstRedeemCode", ctx, refID)}
}

func (_c *MockEZClient_GetFirstRedeemCode_Call) Run(run func(ctx context.Context, refID string)) *MockEZClient_GetFirstRedeemCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEZClient_GetFirstRedeemCode_Call) Return(s string, err error) *MockEZClient_GetFirstRedeemCode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEZClient_GetFirstRedeemCode_Call) RunAndReturn(run func(ctx context.Context, refID string) (string, error)) *MockEZClient_GetFirstRedeemCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockEZClient
func (_mock *MockEZClient) GetOrder(ctx context.Context, refID string) (*port.Order, error) {
	ret := _mock.Called(ctx, refID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *port.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*port.Order, error)); ok {
		return returnFunc(ctx, refID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *port.Order); ok {
		r0 = returnFunc(ctx, refID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEZClient_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockEZClient_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - refID string
func (_e *MockEZClient_Expecter) GetOrder(ctx interface{}, refID interface{}) *MockEZClient_GetOrder_Call {
	return &MockEZClient_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, refID)}
}

func (_c *MockEZClient_GetOrder_Call) Run(run func(ctx context.Context, refID string)) *MockEZClient_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEZClient_GetOrder_Call) Return(order *port.Order, err error) *MockEZClient_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockEZClient_GetOrder_Call) RunAndReturn(run func(ctx context.Context, refID string) (*port.Order, error)) *MockEZClient_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}
