// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderReservation is the predicate function for orderreservation builders.
type OrderReservation func(*sql.Selector)
