// Code generated by ent, DO NOT EDIT.

package orderreservation

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the orderreservation type in the database.
	Label = "order_reservation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRefID holds the string denoting the ref_id field in the database.
	FieldRefID = "ref_id"
	// FieldRefSource holds the string denoting the ref_source field in the database.
	FieldRefSource = "ref_source"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// Table holds the table name of the orderreservation in the database.
	Table = "order_reservations"
)

// Columns holds all SQL columns for orderreservation fields.
var Columns = []string{
	FieldID,
	FieldRefID,
	FieldRefSource,
	FieldCreatedAt,
	FieldUsedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RefIDValidator is a validator for the "ref_id" field. It is called by the builders before save.
	RefIDValidator func(string) error
	// RefSourceValidator is a validator for the "ref_source" field. It is called by the builders before save.
	RefSourceValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the OrderReservation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRefID orders the results by the ref_id field.
func ByRefID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefID, opts...).ToFunc()
}

// ByRefSource orders the results by the ref_source field.
func ByRefSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefSource, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}
