// Code generated by ent, DO NOT EDIT.

package orderreservation

import (
	"orm/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLTE(FieldID, id))
}

// RefID applies equality check predicate on the "ref_id" field. It's identical to RefIDEQ.
func RefID(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldRefID, v))
}

// RefSource applies equality check predicate on the "ref_source" field. It's identical to RefSourceEQ.
func RefSource(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldRefSource, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldUsedAt, v))
}

// RefIDEQ applies the EQ predicate on the "ref_id" field.
func RefIDEQ(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldRefID, v))
}

// RefIDNEQ applies the NEQ predicate on the "ref_id" field.
func RefIDNEQ(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNEQ(FieldRefID, v))
}

// RefIDIn applies the In predicate on the "ref_id" field.
func RefIDIn(vs ...string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldIn(FieldRefID, vs...))
}

// RefIDNotIn applies the NotIn predicate on the "ref_id" field.
func RefIDNotIn(vs ...string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNotIn(FieldRefID, vs...))
}

// RefIDGT applies the GT predicate on the "ref_id" field.
func RefIDGT(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGT(FieldRefID, v))
}

// RefIDGTE applies the GTE predicate on the "ref_id" field.
func RefIDGTE(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGTE(FieldRefID, v))
}

// RefIDLT applies the LT predicate on the "ref_id" field.
func RefIDLT(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLT(FieldRefID, v))
}

// RefIDLTE applies the LTE predicate on the "ref_id" field.
func RefIDLTE(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLTE(FieldRefID, v))
}

// RefIDContains applies the Contains predicate on the "ref_id" field.
func RefIDContains(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldContains(FieldRefID, v))
}

// RefIDHasPrefix applies the HasPrefix predicate on the "ref_id" field.
func RefIDHasPrefix(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldHasPrefix(FieldRefID, v))
}

// RefIDHasSuffix applies the HasSuffix predicate on the "ref_id" field.
func RefIDHasSuffix(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldHasSuffix(FieldRefID, v))
}

// RefIDEqualFold applies the EqualFold predicate on the "ref_id" field.
func RefIDEqualFold(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEqualFold(FieldRefID, v))
}

// RefIDContainsFold applies the ContainsFold predicate on the "ref_id" field.
func RefIDContainsFold(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldContainsFold(FieldRefID, v))
}

// RefSourceEQ applies the EQ predicate on the "ref_source" field.
func RefSourceEQ(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldRefSource, v))
}

// RefSourceNEQ applies the NEQ predicate on the "ref_source" field.
func RefSourceNEQ(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNEQ(FieldRefSource, v))
}

// RefSourceIn applies the In predicate on the "ref_source" field.
func RefSourceIn(vs ...string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldIn(FieldRefSource, vs...))
}

// RefSourceNotIn applies the NotIn predicate on the "ref_source" field.
func RefSourceNotIn(vs ...string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNotIn(FieldRefSource, vs...))
}

// RefSourceGT applies the GT predicate on the "ref_source" field.
func RefSourceGT(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGT(FieldRefSource, v))
}

// RefSourceGTE applies the GTE predicate on the "ref_source" field.
func RefSourceGTE(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGTE(FieldRefSource, v))
}

// RefSourceLT applies the LT predicate on the "ref_source" field.
func RefSourceLT(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLT(FieldRefSource, v))
}

// RefSourceLTE applies the LTE predicate on the "ref_source" field.
func RefSourceLTE(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLTE(FieldRefSource, v))
}

// RefSourceContains applies the Contains predicate on the "ref_source" field.
func RefSourceContains(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldContains(FieldRefSource, v))
}

// RefSourceHasPrefix applies the HasPrefix predicate on the "ref_source" field.
func RefSourceHasPrefix(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldHasPrefix(FieldRefSource, v))
}

// RefSourceHasSuffix applies the HasSuffix predicate on the "ref_source" field.
func RefSourceHasSuffix(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldHasSuffix(FieldRefSource, v))
}

// RefSourceEqualFold applies the EqualFold predicate on the "ref_source" field.
func RefSourceEqualFold(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEqualFold(FieldRefSource, v))
}

// RefSourceContainsFold applies the ContainsFold predicate on the "ref_source" field.
func RefSourceContainsFold(v string) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldContainsFold(FieldRefSource, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNotNull(FieldCreatedAt))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.OrderReservation {
	return predicate.OrderReservation(sql.FieldNotNull(FieldUsedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrderReservation) predicate.OrderReservation {
	return predicate.OrderReservation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrderReservation) predicate.OrderReservation {
	return predicate.OrderReservation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrderReservation) predicate.OrderReservation {
	return predicate.OrderReservation(sql.NotPredicates(p))
}
