/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// OrderStatus : PROCESSING - The order is currently being processed. COMPLETED - The order has been completed successfully. CANCELLED - The order has been cancelled and will not be processed. 
type OrderStatus string

// List of OrderStatus
const (
	PROCESSING_OrderStatus OrderStatus = "PROCESSING"
	COMPLETED_OrderStatus OrderStatus = "COMPLETED"
	CANCELLED_OrderStatus OrderStatus = "CANCELLED"
)
