/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ExchangeRatesPayload struct {
	// ISO-8601 timestamp of the latest rate update (UTC).
	UpdatedAt time.Time `json:"updatedAt"`
	// Platform-supported currencies (ISO-4217).
	ProductCurrencies []string `json:"productCurrencies"`
	// List of EZ Rates for currency pairs.
	Rates []ExchangeRate `json:"rates"`
}
