/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductResponse struct {
	// The Stock Keeping Unit identifier for the product.
	Sku string `json:"sku"`
	// The name of the product.
	Name string `json:"name"`
	// The brand of the product.
	Brand string `json:"brand"`
	// The category of the brand.
	BrandCategory string `json:"brandCategory,omitempty"`
	// The sub-category of the brand.
	BrandSubCategory string `json:"brandSubCategory,omitempty"`
	// List of product types.
	Types []string `json:"types"`
	Format *ProductFormat `json:"format"`
	// The country for which the product is available.
	Country string `json:"country,omitempty"`
	// The 3-letter currency code (ISO-4217).
	Currency string `json:"currency"`
	// The URL of the image representing the product.
	ImageUrl string `json:"imageUrl,omitempty"`
	Prices []PriceResponse `json:"prices"`
	// The face value of the product.
	FaceValue string `json:"faceValue"`
	// The percentage off the face value of the product.
	PercentageOffFaceValue string `json:"percentageOffFaceValue"`
	// Whether the CreateInstantOrder API can be used for instant order and fulfillment.
	IsInstantDeliverySupported bool `json:"isInstantDeliverySupported"`
	Descriptions []string `json:"descriptions"`
	Instructions []string `json:"instructions"`
	TermConditions []string `json:"termConditions"`
}
