/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CodeResponse struct {
	// The unique identifier of the stock.
	StockId int32       `json:"stockId"`
	Status  *CodeStatus `json:"status"`
	// The redeemable code for the product (can be null if not available).
	RedeemCode string `json:"redeemCode,omitempty"`
	// The PIN code for the product (can be null if not available).
	PinCode int32 `json:"pinCode,omitempty"`
}
