/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetCodesProductResponse struct {
	// The SKU of the product.
	Sku string `json:"sku"`
	// The quantity of the product.
	Quantity int32 `json:"quantity"`
	// List of codes in the product.
	Codes []CodeResponse `json:"codes"`
}
