/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateInstantOrderRequest struct {
	// The order number assigned by the client, used for tracking and reference purposes.
	ClientOrderNumber string `json:"clientOrderNumber,omitempty"`
	// Enable to prevent duplicate clientOrderNumber.
	EnableClientOrderNumberDupCheck bool `json:"enableClientOrderNumberDupCheck,omitempty"`
	// The Stock Keeping Unit identifier for the product.
	Sku string `json:"sku"`
	// Settlement currency (ISO-4217). Required only when the product currency is not in the customer's balance currencies. 
	PayWithCurrency string `json:"payWithCurrency,omitempty"`
}
