/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrderProductResponseGetOrders struct {
	// The SKU of the product.
	Sku string `json:"sku"`
	// The quantity of the product.
	Quantity int32 `json:"quantity"`
	UnitPrice *MoneyResponse `json:"unitPrice"`
	TotalPrice *MoneyResponse `json:"totalPrice"`
	Status *OrderStatus `json:"status"`
}
