/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductsPaginationResponse struct {
	Items []ProductResponse `json:"items"`
	// Total number of items available.
	Total int32 `json:"total"`
	// Current page number.
	Page int32 `json:"page"`
	// Number of items per page.
	PageSize int32 `json:"pageSize"`
	// Total number of pages available.
	TotalPage int32 `json:"totalPage"`
}
