/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2005 struct {
	Data *ExchangeRatesPayload `json:"data"`
	// Unique identifier assigned to each request for tracking purposes.
	RequestId string `json:"requestId"`
}
