/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorResponse struct {
	Error_ string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
	ClientOrderNumber string `json:"clientOrderNumber,omitempty"`
}
