/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExchangeRate struct {
	// Currency pair in BASEQUOTE format (e.g., USDCAD).
	Pair string `json:"pair"`
	// Base currency (ISO-4217).
	Base string `json:"base"`
	// Quote currency (ISO-4217).
	Quote string `json:"quote"`
	// EZ Rate with 4 decimal places (e.g., \"1.4102\").
	Rate string `json:"rate"`
}
