/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type OrderResponse struct {
	// The transaction identifier.
	TransactionId string `json:"transactionId"`
	// The client's order number.
	ClientOrderNumber string `json:"clientOrderNumber"`
	// The currency used to settle/charge the order (Create Bulk/Instant only).
	PayWithCurrency string `json:"payWithCurrency,omitempty"`
	GrandTotal *MoneyResponse `json:"grandTotal"`
	// Timestamp of when the order was created.
	CreatedAt time.Time `json:"createdAt"`
	Status *OrderStatus `json:"status"`
	Products []OrderProductResponse `json:"products"`
	// Summary of FX pairs/rates when cross-currency conversion is applied. Omitted for same-currency orders.
	FxSummary []FxEntry `json:"fxSummary,omitempty"`
}
