/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BalanceResponse struct {
	// The balance amount.
	Balance string `json:"balance"`
	// The 3-letter currency code (ISO-4217).
	Currency string `json:"currency"`
}
