/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CodeStatus string

// List of CodeStatus
const (
	PROCESSING_CodeStatus CodeStatus = "PROCESSING"
	COMPLETED_CodeStatus CodeStatus = "COMPLETED"
)
