/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PriceResponse struct {
	// The price of the product.
	Price string `json:"price"`
	// The minimum quantity for which the price is applicable.
	FromQuantity int32 `json:"fromQuantity"`
	// The maximum quantity for which the price is applicable (null indicates no limit).
	ToQuantity int32 `json:"toQuantity,omitempty"`
}
