/*
 * EZ Cards API Reference V2
 *
 * B2B Digital Gift Cards Provider - API Reference V2
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// ProductFormat : D = Digital, P = Physical
type ProductFormat string

// List of ProductFormat
const (
	D_ProductFormat ProductFormat = "D"
	P_ProductFormat ProductFormat = "P"
)
