// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "ref_id", Type: field.TypeString},
		{Name: "ref_source", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PROCESSING", "COMPLETED", "CANCELLED"}},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "order_ref_source_ref_id_status",
				Unique:  false,
				Columns: []*schema.Column{OrdersColumns[2], OrdersColumns[1], OrdersColumns[3]},
			},
			{
				Name:    "order_status",
				Unique:  false,
				Columns: []*schema.Column{OrdersColumns[3]},
			},
		},
	}
	// OrderReservationsColumns holds the columns for the "order_reservations" table.
	OrderReservationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ref_id", Type: field.TypeString},
		{Name: "ref_source", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
	}
	// OrderReservationsTable holds the schema information for the "order_reservations" table.
	OrderReservationsTable = &schema.Table{
		Name:       "order_reservations",
		Columns:    OrderReservationsColumns,
		PrimaryKey: []*schema.Column{OrderReservationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "orderreservation_ref_source_ref_id",
				Unique:  true,
				Columns: []*schema.Column{OrderReservationsColumns[2], OrderReservationsColumns[1]},
			},
			{
				Name:    "orderreservation_ref_source_used_at",
				Unique:  false,
				Columns: []*schema.Column{OrderReservationsColumns[2], OrderReservationsColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrdersTable,
		OrderReservationsTable,
	}
)

func init() {
	OrderReservationsTable.Annotation = &entsql.Annotation{
		Table: "order_reservations",
	}
}
